repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: end-of-file-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
    - id: check-json
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: detect-private-key
    - id: check-added-large-files
      args: [--maxkb=10000]


  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=120]
