# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 'Automatic: On Push & PR'

on:
  push:
    branches: [ main, feat/**, feature/**, chore/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_checkout:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changedfiles }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Echo changed .py files
      id: changes
      run: |
        echo "::set-output name=changedfiles::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.base.sha }} ${{ github.sha }} | grep .py$)"


  lint:
    runs-on: ubuntu-latest
    needs: build_and_checkout
    # if: ${{ build_and_checkout.outputs.changes }}
    steps:
      - name: Echo changed files
        run: |
          echo ${{ build_and_checkout.outputs.changes }}
      - name: Lint with pylint
        run: |
          pylint ${{ build_and_checkout.outputs.changes }}
