# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# name: 'Automatic: On Push & PR'

# on:
#   push:
#     branches: [ main, feat/**, feature/**, chore/**, fix/** ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build_and_checkout:
#     runs-on: ubuntu-latest
#     # outputs:
#     #   changedfiles: ${{ steps.changes.outputs.changedfiles }}

#     steps:
#     - name: Checkout out
#       uses: actions/checkout@v2
#       with:
#         fetch-depth: 0

#     - name: Set up Python 3.9
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9

#     - name: Checkout ouroboros
#       uses: actions/checkout@v2
#       with:
#         repository: sigma21/ouroboros
#         token: ${{ secrets.OUROBOROS_PAT }} 
#         path: ouroboros

#     - name: Install ouroboros
#       run: |
#         pip install ./ouroboros
#         pip list

#     - name: Run filtering
#       run: |
#         python -c "from ouroboros.feed_filter import apply_filter; apply_filter(mrd_file_path='./code/feed.json', target_schema_path='./code/target.json', out_path='./code/filtered_feed.json')"

#     - name: Check and read content
#       run: |
#         ls
#         ls ./code
#         cat ./code/filtered_feed.json