# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 'Automatic: On Push & PR'

on:
  push:
    branches: [ main, feat/**, feature/**, chore/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_checkout:
    runs-on: ubuntu-latest
    # outputs:
    #   changedfiles: ${{ steps.changes.outputs.changedfiles }}

    steps:
    - name: Checkout out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install --upgrade git+git://github.com/datasingularity/ouroboros.git
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi/

    - name: Check changes
      id: changes
      run: |
        echo "::set-output name=changedfiles::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.base.sha }} ${{ github.sha }} | grep .py$)"


    - name: Echo changed .py files
      run: |
        echo ${{ steps.changes.outputs.changedfiles }}

    # - name: Lint
    #   run: |
    #     pylint ${{ steps.changes.outputs.changedfiles }}
