# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # with:
      #   fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Echo changed .py files
      id: changes
      # run: |
        # echo $(git diff --name-only --diff-filter=d refs/remotes/origin/main..HEAD | grep -E "(.py$)")
      run: |
        echo "::set-output name=changedfiles::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .py$)"


    - name: Lint with pylint
      if: ${{ steps.changes.outputs.changedfiles }}
      # run: |
      #   pylint $(git diff --name-only --diff-filter=d refs/remotes/origin/main..HEAD | grep -E "(.py$)")
      run: |
        pylint ${{ changes.outputs.changedfiles }}
