name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run step only if directory has been updated
#         if: ${{ github.event_name == 'push' && github.event.compare }}
        # Replace 'path/to/directory/**' with the actual path to your directory
        if: ${{ contains(github.event.compare, 'code/**') }}
        run: |
          echo "Directory has been updated"
